// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: s3minio.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"` // raw file bytes
	Bucket        string                 `protobuf:"bytes,5,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	Expires       uint32                 `protobuf:"varint,7,opt,name=expires,proto3" json:"expires,omitempty"`
	UserId        int64                  `protobuf:"varint,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MerchantId    int64                  `protobuf:"varint,9,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_s3minio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s3minio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_s3minio_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UploadRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *UploadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadRequest) GetExpires() uint32 {
	if x != nil {
		return x.Expires
	}
	return 0
}

func (x *UploadRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UploadRequest) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data          *UploadData            `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_s3minio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s3minio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_s3minio_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UploadResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UploadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadResponse) GetData() *UploadData {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	PresignedUrl  string                 `protobuf:"bytes,5,opt,name=presigned_url,json=presignedUrl,proto3" json:"presigned_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadData) Reset() {
	*x = UploadData{}
	mi := &file_s3minio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadData) ProtoMessage() {}

func (x *UploadData) ProtoReflect() protoreflect.Message {
	mi := &file_s3minio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadData.ProtoReflect.Descriptor instead.
func (*UploadData) Descriptor() ([]byte, []int) {
	return file_s3minio_proto_rawDescGZIP(), []int{2}
}

func (x *UploadData) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *UploadData) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadData) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadData) GetPresignedUrl() string {
	if x != nil {
		return x.PresignedUrl
	}
	return ""
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        string                 `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"` // filename or url
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Expires       int32                  `protobuf:"varint,4,opt,name=expires,proto3" json:"expires,omitempty"`
	UserId        int64                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MerchantId    int64                  `protobuf:"varint,6,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_s3minio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s3minio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_s3minio_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadRequest) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *DownloadRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *DownloadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DownloadRequest) GetExpires() int32 {
	if x != nil {
		return x.Expires
	}
	return 0
}

func (x *DownloadRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DownloadRequest) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type DownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_s3minio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s3minio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_s3minio_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DownloadResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DownloadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DownloadResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_s3minio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s3minio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_s3minio_proto_rawDescGZIP(), []int{5}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_s3minio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s3minio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_s3minio_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_s3minio_proto protoreflect.FileDescriptor

const file_s3minio_proto_rawDesc = "" +
	"\n" +
	"\rs3minio.proto\x12\as3minio\"\xfc\x01\n" +
	"\rUploadRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12\x16\n" +
	"\x06bucket\x18\x05 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x18\n" +
	"\aexpires\x18\a \x01(\rR\aexpires\x12\x17\n" +
	"\auser_id\x18\b \x01(\x03R\x06userId\x12\x1f\n" +
	"\vmerchant_id\x18\t \x01(\x03R\n" +
	"merchantId\"\x7f\n" +
	"\x0eUploadResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12'\n" +
	"\x04data\x18\x04 \x01(\v2\x13.s3minio.UploadDataR\x04data\"\x8b\x01\n" +
	"\n" +
	"UploadData\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12#\n" +
	"\rpresigned_url\x18\x05 \x01(\tR\fpresignedUrl\"\xa9\x01\n" +
	"\x0fDownloadRequest\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x18\n" +
	"\aexpires\x18\x04 \x01(\x05R\aexpires\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vmerchant_id\x18\x06 \x01(\x03R\n" +
	"merchantId\"l\n" +
	"\x10DownloadResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xe0\x02\n" +
	"\x0eS3MinIOService\x12=\n" +
	"\x06Upload\x12\x16.s3minio.UploadRequest\x1a\x17.s3minio.UploadResponse\"\x00(\x01\x12?\n" +
	"\bDownload\x12\x18.s3minio.DownloadRequest\x1a\x19.s3minio.DownloadResponse\x12K\n" +
	"\x14GeneratePresignedUrl\x12\x18.s3minio.DownloadRequest\x1a\x19.s3minio.DownloadResponse\x12F\n" +
	"\x0fGenerateViewUrl\x12\x18.s3minio.DownloadRequest\x1a\x19.s3minio.DownloadResponse\x129\n" +
	"\x06Health\x12\x16.s3minio.HealthRequest\x1a\x17.s3minio.HealthResponseB\fZ\n" +
	"grpc/pb;pbb\x06proto3"

var (
	file_s3minio_proto_rawDescOnce sync.Once
	file_s3minio_proto_rawDescData []byte
)

func file_s3minio_proto_rawDescGZIP() []byte {
	file_s3minio_proto_rawDescOnce.Do(func() {
		file_s3minio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_s3minio_proto_rawDesc), len(file_s3minio_proto_rawDesc)))
	})
	return file_s3minio_proto_rawDescData
}

var file_s3minio_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_s3minio_proto_goTypes = []any{
	(*UploadRequest)(nil),    // 0: s3minio.UploadRequest
	(*UploadResponse)(nil),   // 1: s3minio.UploadResponse
	(*UploadData)(nil),       // 2: s3minio.UploadData
	(*DownloadRequest)(nil),  // 3: s3minio.DownloadRequest
	(*DownloadResponse)(nil), // 4: s3minio.DownloadResponse
	(*HealthRequest)(nil),    // 5: s3minio.HealthRequest
	(*HealthResponse)(nil),   // 6: s3minio.HealthResponse
}
var file_s3minio_proto_depIdxs = []int32{
	2, // 0: s3minio.UploadResponse.data:type_name -> s3minio.UploadData
	0, // 1: s3minio.S3MinIOService.Upload:input_type -> s3minio.UploadRequest
	3, // 2: s3minio.S3MinIOService.Download:input_type -> s3minio.DownloadRequest
	3, // 3: s3minio.S3MinIOService.GeneratePresignedUrl:input_type -> s3minio.DownloadRequest
	3, // 4: s3minio.S3MinIOService.GenerateViewUrl:input_type -> s3minio.DownloadRequest
	5, // 5: s3minio.S3MinIOService.Health:input_type -> s3minio.HealthRequest
	1, // 6: s3minio.S3MinIOService.Upload:output_type -> s3minio.UploadResponse
	4, // 7: s3minio.S3MinIOService.Download:output_type -> s3minio.DownloadResponse
	4, // 8: s3minio.S3MinIOService.GeneratePresignedUrl:output_type -> s3minio.DownloadResponse
	4, // 9: s3minio.S3MinIOService.GenerateViewUrl:output_type -> s3minio.DownloadResponse
	6, // 10: s3minio.S3MinIOService.Health:output_type -> s3minio.HealthResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_s3minio_proto_init() }
func file_s3minio_proto_init() {
	if File_s3minio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_s3minio_proto_rawDesc), len(file_s3minio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_s3minio_proto_goTypes,
		DependencyIndexes: file_s3minio_proto_depIdxs,
		MessageInfos:      file_s3minio_proto_msgTypes,
	}.Build()
	File_s3minio_proto = out.File
	file_s3minio_proto_goTypes = nil
	file_s3minio_proto_depIdxs = nil
}
