// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: s3minio.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	S3MinIOService_Upload_FullMethodName               = "/s3minio.S3MinIOService/Upload"
	S3MinIOService_Download_FullMethodName             = "/s3minio.S3MinIOService/Download"
	S3MinIOService_GeneratePresignedUrl_FullMethodName = "/s3minio.S3MinIOService/GeneratePresignedUrl"
	S3MinIOService_GenerateViewUrl_FullMethodName      = "/s3minio.S3MinIOService/GenerateViewUrl"
	S3MinIOService_Health_FullMethodName               = "/s3minio.S3MinIOService/Health"
)

// S3MinIOServiceClient is the client API for S3MinIOService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// S3MinIOService provides basic upload/download and health RPCs as a sample.
type S3MinIOServiceClient interface {
	// Upload a file (binary content in request)
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadRequest, UploadResponse], error)
	// Download a file by bucket/path/filename
	Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*DownloadResponse, error)
	// Generate a presigned URL (same behavior as Download URL generation)
	GeneratePresignedUrl(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*DownloadResponse, error)
	// Generate frontend view URL (API_URL + API_VIEW_PATH)
	GenerateViewUrl(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*DownloadResponse, error)
	// Health check for the gRPC service
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type s3MinIOServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewS3MinIOServiceClient(cc grpc.ClientConnInterface) S3MinIOServiceClient {
	return &s3MinIOServiceClient{cc}
}

func (c *s3MinIOServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadRequest, UploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &S3MinIOService_ServiceDesc.Streams[0], S3MinIOService_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadRequest, UploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type S3MinIOService_UploadClient = grpc.ClientStreamingClient[UploadRequest, UploadResponse]

func (c *s3MinIOServiceClient) Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*DownloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadResponse)
	err := c.cc.Invoke(ctx, S3MinIOService_Download_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3MinIOServiceClient) GeneratePresignedUrl(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*DownloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadResponse)
	err := c.cc.Invoke(ctx, S3MinIOService_GeneratePresignedUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3MinIOServiceClient) GenerateViewUrl(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*DownloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadResponse)
	err := c.cc.Invoke(ctx, S3MinIOService_GenerateViewUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3MinIOServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, S3MinIOService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// S3MinIOServiceServer is the server API for S3MinIOService service.
// All implementations must embed UnimplementedS3MinIOServiceServer
// for forward compatibility.
//
// S3MinIOService provides basic upload/download and health RPCs as a sample.
type S3MinIOServiceServer interface {
	// Upload a file (binary content in request)
	Upload(grpc.ClientStreamingServer[UploadRequest, UploadResponse]) error
	// Download a file by bucket/path/filename
	Download(context.Context, *DownloadRequest) (*DownloadResponse, error)
	// Generate a presigned URL (same behavior as Download URL generation)
	GeneratePresignedUrl(context.Context, *DownloadRequest) (*DownloadResponse, error)
	// Generate frontend view URL (API_URL + API_VIEW_PATH)
	GenerateViewUrl(context.Context, *DownloadRequest) (*DownloadResponse, error)
	// Health check for the gRPC service
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedS3MinIOServiceServer()
}

// UnimplementedS3MinIOServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedS3MinIOServiceServer struct{}

func (UnimplementedS3MinIOServiceServer) Upload(grpc.ClientStreamingServer[UploadRequest, UploadResponse]) error {
	return status.Error(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedS3MinIOServiceServer) Download(context.Context, *DownloadRequest) (*DownloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedS3MinIOServiceServer) GeneratePresignedUrl(context.Context, *DownloadRequest) (*DownloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GeneratePresignedUrl not implemented")
}
func (UnimplementedS3MinIOServiceServer) GenerateViewUrl(context.Context, *DownloadRequest) (*DownloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateViewUrl not implemented")
}
func (UnimplementedS3MinIOServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedS3MinIOServiceServer) mustEmbedUnimplementedS3MinIOServiceServer() {}
func (UnimplementedS3MinIOServiceServer) testEmbeddedByValue()                        {}

// UnsafeS3MinIOServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to S3MinIOServiceServer will
// result in compilation errors.
type UnsafeS3MinIOServiceServer interface {
	mustEmbedUnimplementedS3MinIOServiceServer()
}

func RegisterS3MinIOServiceServer(s grpc.ServiceRegistrar, srv S3MinIOServiceServer) {
	// If the following call panics, it indicates UnimplementedS3MinIOServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&S3MinIOService_ServiceDesc, srv)
}

func _S3MinIOService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(S3MinIOServiceServer).Upload(&grpc.GenericServerStream[UploadRequest, UploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type S3MinIOService_UploadServer = grpc.ClientStreamingServer[UploadRequest, UploadResponse]

func _S3MinIOService_Download_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3MinIOServiceServer).Download(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3MinIOService_Download_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3MinIOServiceServer).Download(ctx, req.(*DownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3MinIOService_GeneratePresignedUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3MinIOServiceServer).GeneratePresignedUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3MinIOService_GeneratePresignedUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3MinIOServiceServer).GeneratePresignedUrl(ctx, req.(*DownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3MinIOService_GenerateViewUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3MinIOServiceServer).GenerateViewUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3MinIOService_GenerateViewUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3MinIOServiceServer).GenerateViewUrl(ctx, req.(*DownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3MinIOService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3MinIOServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3MinIOService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3MinIOServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// S3MinIOService_ServiceDesc is the grpc.ServiceDesc for S3MinIOService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var S3MinIOService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "s3minio.S3MinIOService",
	HandlerType: (*S3MinIOServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Download",
			Handler:    _S3MinIOService_Download_Handler,
		},
		{
			MethodName: "GeneratePresignedUrl",
			Handler:    _S3MinIOService_GeneratePresignedUrl_Handler,
		},
		{
			MethodName: "GenerateViewUrl",
			Handler:    _S3MinIOService_GenerateViewUrl_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _S3MinIOService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _S3MinIOService_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "s3minio.proto",
}
